"""create security events and alerts

Revision ID: 1c1e8aa9d19a
Revises: 
Create Date: 2026-09-22 14:29:56.702476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1c1e8aa9d19a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('rule_id', sa.String(length=100), nullable=False),
    sa.Column('rule_version', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('user_name', sa.String(length=255), nullable=True),
    sa.Column('source_ip', sa.String(length=64), nullable=True),
    sa.Column('source_host', sa.String(length=255), nullable=True),
    sa.Column('destination_host', sa.String(length=255), nullable=True),
    sa.Column('evidence_record_ids', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('evidence_event_codes', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('mitre_techniques', postgresql.ARRAY(sa.String()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alerts_created_at', 'alerts', ['created_at'], unique=False)
    op.create_index('ix_alerts_rule_id', 'alerts', ['rule_id'], unique=False)
    op.create_index('ix_alerts_severity', 'alerts', ['severity'], unique=False)
    op.create_table('security_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('schema_version', sa.String(length=20), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('event_code', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('outcome', sa.String(length=50), nullable=True),
    sa.Column('source_provider', sa.String(length=255), nullable=True),
    sa.Column('source_channel', sa.String(length=255), nullable=True),
    sa.Column('source_dataset', sa.String(length=255), nullable=True),
    sa.Column('source_record_id', sa.String(length=255), nullable=True),
    sa.Column('host_name', sa.String(length=255), nullable=True),
    sa.Column('user_name', sa.String(length=255), nullable=True),
    sa.Column('user_domain', sa.String(length=255), nullable=True),
    sa.Column('user_sid', sa.String(length=255), nullable=True),
    sa.Column('source_host', sa.String(length=255), nullable=True),
    sa.Column('source_ip', sa.String(length=64), nullable=True),
    sa.Column('destination_host', sa.String(length=255), nullable=True),
    sa.Column('destination_ip', sa.String(length=64), nullable=True),
    sa.Column('raw_event', sa.Text(), nullable=False),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_security_events_event_code', 'security_events', ['event_code'], unique=False)
    op.create_index('ix_security_events_occurred_at', 'security_events', ['occurred_at'], unique=False)
    op.create_index('ix_security_events_source_ip', 'security_events', ['source_ip'], unique=False)
    op.create_index('ix_security_events_user_name', 'security_events', ['user_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_security_events_user_name', table_name='security_events')
    op.drop_index('ix_security_events_source_ip', table_name='security_events')
    op.drop_index('ix_security_events_occurred_at', table_name='security_events')
    op.drop_index('ix_security_events_event_code', table_name='security_events')
    op.drop_table('security_events')
    op.drop_index('ix_alerts_severity', table_name='alerts')
    op.drop_index('ix_alerts_rule_id', table_name='alerts')
    op.drop_index('ix_alerts_created_at', table_name='alerts')
    op.drop_table('alerts')
    # ### end Alembic commands ###
