"""fix security event source identity

Revision ID: 918c2c0ef316
Revises: 4a89e6322e50
Create Date: 2026-09-22 14:40:06.747311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '918c2c0ef316'
down_revision: Union[str, Sequence[str], None] = '4a89e6322e50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_security_events_source_record'), 'security_events', type_='unique')
    op.create_unique_constraint('uq_security_events_source_identity', 'security_events', ['source_dataset', 'source_channel', 'host_name', 'source_record_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_security_events_source_identity', 'security_events', type_='unique')
    op.create_unique_constraint(op.f('uq_security_events_source_record'), 'security_events', ['source_dataset', 'source_record_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
